
###
GET http://localhost:8080/api/v1/policies/premiumCalculator
Content-Type: application/json

{
  "number": "123",
  "status": "REGISTERED",
  "policyObjects": [
    {
      "name" : "House",
      "policySubObject" : [
        {
          "name" : "TV",
          "insuredSum" : 450,
          "riskType" : "FIRE"
        },
        {
          "name" : "Laptop",
          "insuredSum" : 50,
          "riskType" : "FIRE"
        },
        {
          "name" : "Mobile",
          "insuredSum" : 102.51,
          "riskType" : "THEFT"
        }
      ]

    }
  ]

}


###
GET http://localhost:8080/api/v1/policies/premiumCalculator
Content-Type: application/json

{
  "number": "456",
  "status": "REGISTERED",
  "policyObjects": [
    {
      "name" : "House",
      "policySubObject" : [
        {
          "name" : "TV",
          "insuredSum" : 50,
          "riskType" : "FIRE"
        },
        {
          "name" : "Laptop",
          "insuredSum" : 50,
          "riskType" : "FIRE"
        },
        {
          "name" : "Mobile",
          "insuredSum" : 8,
          "riskType" : "THEFT"
        }
      ]

    }
  ]

}